obtain shell from within script
dsa-ou/virtual-env pull request #3
Opened 2023-03-04 21:37 UTC by densnow

Most of the discussion about this can be found under issue #2. The change is mostly the line that uses the [ps](https://www.ibm.com/docs/en/aix/7.1?topic=p-ps-command) command, and the parent process ID ([PPID](https://www.baeldung.com/linux/pid-tid-ppid)) to determine the name of the shell that invoked the script.

2023-03-15 20:44 UTC, mwermelinger commented
Unfortunately, on macOS Monterey, the `ps` command has to be invoked as `ps $PPID -o comm=` or as `ps $PPID -o command` because it doesn't have the `-q` option or the `cmd` keyword. Do any of these also work on your system?

2023-03-15 23:23 UTC, densnow commented
The 2 ways you have suggested work for me but with the arguments in a different order e.g `ps -o comm= $PPID` works and so does `ps -o command $PPID`

2023-03-16 10:56 UTC, mwermelinger requested changes
Thanks for doing this. Just minor changes required and I'll merge this.

2023-03-16 10:56 UTC, mwermelinger commented on README.md
> +7. Create an environment by typing ``./createnv.sh <name>``.
Here and elsewhere: the double backticks can now become a single backtracks because the inner backpack of the echo command has gone.

2023-03-16 10:56 UTC, mwermelinger commented on createnv.sh
> +
Let's use `ps -o command $PPID` as it works for both of us.

2023-03-16 12:43 UTC, densnow commented
I have added the changes you have requested. I always learn a lot from little challenges like this, so I am happy to help.

2023-03-16 13:20 UTC, mwermelinger approved these changes

2023-03-16 13:21 UTC, merged